### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by CMCDragonkai** [dan-manges/m2node#10]
When running npm install m2node I get this:

```
npm http GET https://registry.npmjs.org/m2node
npm http 304 https://registry.npmjs.org/m2node
npm http GET https://registry.npmjs.org/m2node/-/m2node-0.2.0.tgz
npm http 200 https://registry.npmjs.org/m2node/-/m2node-0.2.0.tgz
npm ERR! ReferenceError: nonStringBundleDependency is not defined
npm ERR!     at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:113:28)
npm ERR!     at Array.filter (native)
npm ERR!     at Object.module.exports.fixBundleDependenciesField (/usr/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:111:27)
npm ERR!     at Object.module.exports.fixDependencies (/usr/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:126:10)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:28:15)
npm ERR!     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:328:33)
npm ERR!     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:252:40
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.11.0-12-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "m2node" "--save"
npm ERR! cwd /www/node
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! type not_defined
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /www/node/npm-debug.log
npm ERR! not ok code 0
```

**Comment by dan-manges** [comment]
Unfortunately I haven't been maintaining `m2node`. If anybody would like to update it, I'll give you access to the package on npm.
